## Configuration file for CAVA.
# Remove the ; to change parameters.

[general]

bars = 50
[input]

method = pipewire
source = spotify_sink.monitor

[output]

method = raw
raw_target = /dev/stdout

data_format = ascii
waveform = 0

[color]

foreground = "#ffffff";

[smoothing]

[eq]
